# Generated by Django 5.2.8 on 2026-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=255)),
                ('year', models.IntegerField(db_index=True)),
                ('price', models.FloatField()),
                ('demand', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Real Estate Data',
                'verbose_name_plural': 'Real Estate Data',
                'indexes': [models.Index(fields=['area', 'year'], name='realestate__area_621c15_idx')],
            },
        ),
    ]
